let projectData = {};

export const city = document.getElementById('city').value;

const baseURLGeo = "http://api.geonames.org/searchJSON?q=";
const baseURLWeatherCurrent = "https://api.weatherbit.io/v2.0/current?";
const baseURLWeatherForecast = "https://api.weatherbit.io/v2.0/forecast/daily?";
const baseURLPixabay = "https://pixabay.com/api/?";

// Create a new date instance dynamically with JS
const d = new Date(); //changed it from let to const
export const newDate = d.getMonth() + 1 + '/' + d.getDate() + '/' + d.getFullYear(); //changed it from let to const

export const depDateFromUser = document.getElementById("departureDate").value;//Now we have to figure out how to do it without getElementById
export const returnDateFromUser = document.getElementById("returnDate").value;

const username = 'salah_2';
const weatherbitAPIKey = '2f3e278d4be24ab6b4e423bc8173692e';
const pixabayAPIKey = '16218326-43ea96121b489407a6f95ba78';

const create_UUID = () => {
    var dt = new Date().getTime();
    var uuid = 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function (c) {
        var r = (dt + Math.random() * 16) % 16 | 0;
        dt = Math.floor(dt / 16);
        return (c == 'x' ? r : (r & 0x3 | 0x8)).toString(16);
    });
    return uuid;
}

const getFunc = async () => {
    const resGeo = await fetch(baseURLGeo + encodeURI(city) + "&username=" + username);

    try {
        const data = await resGeo.json();
        const countryName = data.geonames[0].countryName;
        const latitude = data.geonames[0].lat;
        const longitude = data.geonames[0].lng;
        const daysLeft = timeDiff(newDate, depDateFromUser, returnDateFromUser);

        const resWeather = await fetch(
            ((daysLeft > 7) ? baseURLWeatherForecast : baseURLWeatherCurrent) + "key=" + weatherbitAPIKey + "&lat=" + latitude + "&lon=" + longitude
        );

        const data2 = await resWeather.json();
        const weather = data2.data[0].weather.description;

        const resPixabayPhoto = await fetch(baseURLPixabay + "key=" + pixabayAPIKey + "&q=" + encodeURI(city) + "+tourism&image_type=photo");

        const data3 = await resPixabayPhoto.json();
        const cityPhoto = data3.hits[0].webformatURL;

        // id generated by create_UUID function
        const currentId = create_UUID();

        const tripData = {
            cityPhoto: cityPhoto,
            country: countryName,
            date: newDate,
            depDate: depDateFromUser,
            retDate: returnDateFromUser,
            daysLeft: daysLeft,
            weather: weather,
            temp: (daysLeft > 7) ? {
                low_temp: data2.data[0].low_temp,
                max_temp: data2.data[0].max_temp,
                trueOrFalse: true //For the if statement in updateUI in the client side
            } : {
                    temp: data2.data[0].temp,
                    trueOrFalse: false //For the if statement in updateUI in the client side
                },
            lat: latitude,
            lng: longitude,
            tripId: currentId
        };

        projectData[currentId] = tripData;

        return projectData;

    } catch (error) {
        console.log("error", error);
        //appropriately handle the error
    }
};

export default getFunc;